version: "2"

services:
  zookeeper:
    networks:
      - appNetwork
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/rsvpSample"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    networks:
      - appNetwork    
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/rsvpSample"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  db:
    networks:
      - appNetwork   
    image: mysql
    restart: always
    ports:
      - "9092:9092"
      - "2181:2181"
      - "999:999"
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cities
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

networks:
  appNetwork:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql:
    driver: local
  mysql_config:
    driver: local
